### ISSUE TITLE
Plug in benchmarking data source

### ISSUE THREAD

**Issue by treefridge** [embarg0/WeightedSetPackingLocal#4]
Currently we just have a hardcoded test set  returned from DataSet ;)

**Comment by np-harder** [comment]
I've just noticed, but right now the final result is every single recipe
Final solution: [ R# = 1,  R# = 2,  R# = 3, ...., R# = 449]

The program isn't recognizing the intersections. However, it recognized such intersections in the old, hard-coded data. I'm looking for what the problem is but so far no luck. 

@mplac076 , @embarg0

**Comment by np-harder** [comment]
Never mind!
